KEYWORD_RULES = {
    # General
    'engineering':              ['engineering_nav'],
    'medical':                  ['medical_field_nav'],
    'arts':                     ['explore_arts_science'],
    'science':                  ['explore_arts_science'],
    'courses after 12th':       ['12th_completed'],
    'after 12th':               ['12th_completed'],
    'finished 12th':            ['12th_completed'],
    'completed 12th':           ['12th_completed'],

    # Medical - NEET
    'doctor':                   ['medical_field_nav'],
    'mbbs':                     ['btech_mbbs'],
    'neet':                     ['neet_required_medical'],
    'bds':                      ['btech_bds'],
    'dental':                   ['btech_bds'],
    'ayurveda':                 ['btech_bams'],
    'bams':                     ['btech_bams'],
    'homeopathy':               ['btech_bhms'],
    'bhms':                     ['btech_bhms'],
    'unani':                    ['btech_bums'],
    'siddha':                   ['btech_bsms'],
    'veterinary':               ['btech_bvsc'],
    'physiotherapy':            ['btech_bpt'],
    'bpt':                      ['btech_bpt'],

    # Medical - No NEET
    'without neet':             ['medical_healthcare_noneet'],
    'no neet':                  ['medical_healthcare_noneet'],
    'occupational therapy':     ['btech_bot'],
    'biotechnology':            ['btech_biotech'],
    'microbiology':             ['btech_microbiology'],
    'cardiac':                  ['btech_cardiac'],
    'respiratory':              ['btech_respiratory'],
    'healthcare management':    ['btech_healthcare_mgmt'],

    # Allied Health
    'nursing':                  ['btech_nursing'],
    'gnm':                      ['btech_gnm'],
    'lab technician':           ['btech_mlt'],
    'radiology':                ['btech_radiology'],
    'anesthesia':               ['btech_anesthesia'],
    'physician assistant':      ['btech_physician'],
    'dialysis':                 ['btech_dialysis'],
    'optometry':                ['btech_optometry'],
    'pharmacy':                 ['btech_dpharm'],

    # Engineering - Mechanical
    'mechanical':               ['btech_mechanical_engineering'],
    'automobile':               ['btech_automobile_engineering'],
    'mechatronics':             ['btech_mechatronics_engineering'],
    'robotics':                 ['btech_robotics_automation'],
    'automation':               ['btech_robotics_automation'],
    'manufacturing':            ['btech_production_manufacturing'],
    'production':               ['btech_production_manufacturing'],
    'thermal':                  ['btech_thermal_energy'],
    'metallurgy':               ['btech_materials_metallurgy'],
    'materials':                ['btech_materials_metallurgy'],

    # Engineering - Civil
    'civil':                    ['btech_civil_engineering'],
    'structural':               ['btech_structural_engineering'],
    'construction':             ['btech_construction_mgmt'],
    'environmental engineering':['btech_environmental_engineering'],
    'transportation':           ['btech_transportation_engineering'],

    # Engineering - Computer
    'software':                 ['btech_software_engineering'],
    'cse':                      ['btech_cse'],
    'computer science':         ['btech_cse'],
    'artificial intelligence':  ['btech_ai_ml'],
    'machine learning':         ['btech_ai_ml'],
    'data science':             ['btech_data_science'],
    'cyber security':           ['btech_cyber_security'],
    'cybersecurity':            ['btech_cyber_security'],
    'hacking':                  ['btech_cyber_security'],
    'cloud':                    ['btech_cloud_computing'],
    'big data':                 ['btech_big_data'],
    'iot':                      ['btech_iot'],
    'internet of things':       ['btech_iot'],

    # Engineering - Electrical
    'electrical':               ['btech_eee'],
    'eee':                      ['btech_eee'],
    'electronics':              ['btech_ece'],
    'ece':                      ['btech_ece'],
    'communication':            ['btech_communication'],
    'avionics':                 ['btech_avionics'],
    'biomedical':               ['btech_biomedical'],
    'nanotechnology':           ['btech_nano'],
    'power systems':            ['btech_power'],

    # Arts - Humanities
    'english literature':       ['ba_english_literature'],
    'english language':         ['ba_english_language'],
    'english':                  ['ba_english_literature'],
    'hindi':                    ['ba_hindi'],
    'telugu':                   ['ba_telugu'],
    'malayalam':                ['ba_malayalam'],
    'history':                  ['ba_history'],
    'archaeology':              ['ba_history_archaeology'],
    'ancient history':          ['ba_ancient_history'],
    'philosophy':               ['ba_philosophy'],
    'ethics':                   ['ba_philosophy_ethics'],
    'political science':        ['ba_political_science'],
    'public administration':    ['ba_public_administration'],
    'sociology':                ['ba_sociology'],
    'social work':              ['ba_sociology_social_work'],
    'anthropology':             ['ba_sociology_anthropology'],

    # Arts - Psychology
    'psychology':               ['ba_psychology'],
    'clinical psychology':      ['ba_clinical_psychology'],
    'counselling':              ['ba_counselling_psychology'],
    'counseling':               ['ba_counselling_psychology'],

    # Arts - Journalism
    'journalism':               ['ba_journalism'],
    'mass communication':       ['ba_journalism_mass_comm'],
    'media':                    ['ba_journalism_mass_comm'],
    'digital journalism':       ['ba_digital_journalism'],
    'broadcast':                ['ba_broadcast_journalism'],
    'multimedia':               ['ba_multimedia_journalism'],

    # Arts - Fine Arts
    'fine arts':                ['ba_fine_arts'],
    'visual arts':              ['ba_visual_arts'],
    'music':                    ['ba_music'],
    'dance':                    ['ba_dance'],
    'theatre':                  ['ba_theatre'],
    'animation':                ['ba_animation_vfx'],
    'vfx':                      ['ba_animation_vfx'],

    # Science
    'physics':                  ['bsc_physics'],
    'applied physics':          ['bsc_applied_physics'],
    'chemistry':                ['bsc_chemistry'],
    'biology':                  ['bsc_biology'],
    'mathematics':              ['bsc_math'],
    'maths':                    ['bsc_math'],
    'statistics':               ['bsc_statistics'],
    'bca':                      ['bca'],
    'computer applications':    ['bca'],
    'bsc cs':                   ['bsc_cs'],
    'bsc it':                   ['bsc_it'],
    'information technology':   ['bsc_it'],
}