# Generated by Django 6.0.1 on 2026-02-28 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("stream", models.CharField(blank=True, max_length=100, null=True)),
                ("marks", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("interests", models.TextField(blank=True, null=True)),
                ("preferences", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="chatbot.studentprofile",
                    ),
                ),
            ],
        ),
    ]
