# Generated by Django 6.0.1 on 2026-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_studentprofile_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="ug_degree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
