# Generated by Django 6.0.1 on 2026-03-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_studentprofile_ug_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="course_offset",
            field=models.IntegerField(default=0),
        ),
    ]
