# Generated by Django 6.0.1 on 2026-03-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_studentprofile_course_offset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="course_offset",
        ),
    ]
