# Generated by Django 6.0.3 on 2026-03-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_remove_studentprofile_course_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="current_course_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
