# Generated by Django 6.0.3 on 2026-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_searchhistory_user_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
